name: ocean_eos
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - argopy
  - "erddapy<2.0.0"
  - "pandas<2.0.0"
  - xarray
  - dask
  - netcdf4
  - matplotlib
  - jupyter
  - pystac-client
  - planetary-computer
  - odc-stac
  - scikit-image
